### ISSUE TITLE
The todo list associate with xdma

### ISSUE THREAD

**Issue by IveanEx** [KULeuven-MICAS/snax_cluster#200]
This is the tasks list still need to be done after merging PR#199: 

- [ ] Move reader & writer inside xdma as common cells for snax, and reused by streamer. @xiaoling-yi 
- [ ] Merge **_hw/chisel_acc_** into one sub-directory of **_hw/chisel_**. @xiaoling-yi 
- [ ] Move xdma inside **_snitch_cluster.sv_**, and add AXI interface. @Konste11ation @IveanEx 
- [ ] Automatic generation of snax-xdma-csr-addr.h @IveanEx 
- [ ] Rewrite gen_chisel_file to do the automatic param passing @rgantonio @IveanEx 
- [ ] Move csr_write_soft_switch to common library @IveanEx

**Comment by rgantonio** [comment]
We need to add another list of cleaning up with other things too! Especially the software make files.
