### ISSUE TITLE
Occamy integration TODO list

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snax_cluster#216]
Major TODO
- [x] Make `rtl-gen` separate from build (PR #214)
- [x] Import @xiaoling-yi's SNAX ACC inside the `wrappergen`
  - [x] Change `wrappergen` to `snaxgen`
- [x] Separate cluster targets from accelerator targets. Basically put `_cluster` to target names.
- [x] Check with @IveanEx if it is good for Occamy.
